name: Trigger auto deployment for blah123

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/blah123-AutoDeployTrigger-0dd82f0b-f2bd-4d06-962e-907c9a0a9c23.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BLAH123_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BLAH123_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BLAH123_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: simonj.azurecr.io
          registryUsername: ${{ secrets.BLAH123_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BLAH123_REGISTRY_PASSWORD }}
          containerAppName: blah123
          resourceGroup: simon-demo
          imageToBuild: simonj.azurecr.io/blah123:${{ github.sha }}
          


